# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'JSONMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSONMap
  pod 'Alamofire', '~> 4.5'
  pod 'ObjectMapper', '~> 3.4'
  pod 'AlamofireObjectMapper', '~> 5.2'

end
